name: todo-app

services:
  postgres:
    image: postgres
    container_name: todo-app-postgres
    environment:
      POSTGRES_DB: todo-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - todo-app_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  todo-app_postgres_data: